### ISSUE TITLE
There is no particpants.json file

### ISSUE THREAD

**Issue by YvesMuyaBenda** [szabgab/modiin-co-learning#28]
Hello @szabgab! Since you have removed the participants.json file, I assume the pull request is to be sent  to this repo https://github.com/collab-dev/participants. If so, might you update the book to reflect the changes?

**Comment by szabgab** [comment]
Apparently I moved the repo to https://github.com/collab-dev/participants but have not updated the book yet. I see you found it already.

**Comment by szabgab** [comment]
Fixed it now. It will be in the next edition. Thanks.

**Comment by YvesMuyaBenda** [comment]
Thanks for fixing the book. It will make for a smoother experience for new readers.
